<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>ArenaVirtual</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<MauiEnableXamlCBindingWithSourceCompilation>true</MauiEnableXamlCBindingWithSourceCompilation>
		

		<!-- Display name -->
		<ApplicationTitle>Arena Virtual</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>br.com.raphaellins.arenavirtual</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" Include="Resources\AppIcon\appicon_android.svg" ForegroundFile="Resources\AppIcon\appiconfg_android.svg" BaseSize="512,512" Color="FF5900" />
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="FF5900" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="FF5900" BaseSize="400,400" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="CommunityToolkit.Maui" Version="12.1.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="linqtotwitter" Version="6.15.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.7" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.90" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.7" />
		<PackageReference Include="Refractored.MvvmHelpers" Version="1.6.2" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\Atleta\EditarTimePage.xaml.cs">
	    <DependentUpon>EditarTimePage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Atleta\PartidasPage.xaml.cs">
	    <DependentUpon>PartidasPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Organizador\EditarCampeonatoPage.xaml.cs">
	    <DependentUpon>EditarCampeonatoPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\RegisterPage.xaml.cs">
	    <DependentUpon>RegisterPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="AppShell.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\AlterarImagemPopup.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\AlterarSenhaPopup.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\EditarPerfilPopup.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Atleta\CriarTimePage.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Atleta\EditarTimePage.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Atleta\EntrarTimePage.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Atleta\SolicitacaoTimePage.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\CampeonatoPage\CampeonatoDetailPage.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Components\CampeonatoCard.xaml">
	    <Generator></Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HomePage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PerfilPage.xaml">
	    <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <None Update="AppShell.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	  <None Update="MainPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<PropertyGroup>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>
	
</Project>
