// <auto-generated />
using System;
using ArenaVirtualAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaVirtualAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250929190116_MakeConviteFKsNullable")]
    partial class MakeConviteFKsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArenaVirtualAPI.Models.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailOrganizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatoCampeonato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaveraPremiacao")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LocaisDosJogos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeOrganizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroEquipes")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMaximoEquipes")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizadorId")
                        .HasColumnType("int");

                    b.Property<string>("Regras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneOrganizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTaxaInscricao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConvidadoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdSolicitanteServidor")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdSolicitanteServidor");

                    b.HasIndex("TimeId");

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CapitaoClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CapitaoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("int");

                    b.Property<string>("Regiao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("CapitaoId")
                        .IsUnique()
                        .HasFilter("[CapitaoId] IS NOT NULL");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FaixaOrcamentoPatrocinio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("ImagemPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LinkRedeSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TimeClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.UsuarioCampeonatoFavorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CampeonatoClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioClientAppId", "CampeonatoClientAppId")
                        .IsUnique();

                    b.ToTable("UsuarioCampeonatoFavoritos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Campeonato", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Convite", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("IdSolicitanteServidor");

                    b.HasOne("ArenaVirtualAPI.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");

                    b.Navigation("Solicitante");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Time", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Campeonato", "Campeonato")
                        .WithMany("Times")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Capitao")
                        .WithOne("TimeCapitao")
                        .HasForeignKey("ArenaVirtualAPI.Models.Time", "CapitaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campeonato");

                    b.Navigation("Capitao");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Usuario", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Time", "Time")
                        .WithMany("Membros")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Campeonato", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Time", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Usuario", b =>
                {
                    b.Navigation("TimeCapitao");
                });
#pragma warning restore 612, 618
        }
    }
}
