// <auto-generated />
using System;
using ArenaVirtualAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaVirtualAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20251028212511_NovaMigracaoComRelacionamentosCorrigidos")]
    partial class NovaMigracaoComRelacionamentosCorrigidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArenaVirtualAPI.Models.AvaliacaoArbitro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArbitroId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("JogoId");

                    b.ToTable("AvaliacoesArbitros");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.CampanhaPatrocinio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemPatrocinador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatrocinadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorProposta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("PatrocinadorId");

                    b.ToTable("CampanhasPatrocinios");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailOrganizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatoCampeonato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HaveraPremiacao")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LocaisDosJogos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeOrganizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEquipes")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMaximoEquipes")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizadorId")
                        .HasColumnType("int");

                    b.Property<string>("TelefoneOrganizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTaxaInscricao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConvidadoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdSolicitanteServidor")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdSolicitanteServidor");

                    b.HasIndex("TimeId");

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.EstatisticaPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Arremessos2PontosConvertidos")
                        .HasColumnType("int");

                    b.Property<int>("Arremessos2PontosTentados")
                        .HasColumnType("int");

                    b.Property<int>("Arremessos3PontosConvertidos")
                        .HasColumnType("int");

                    b.Property<int>("Arremessos3PontosTentados")
                        .HasColumnType("int");

                    b.Property<int>("Assistencias")
                        .HasColumnType("int");

                    b.Property<int>("Bloqueios")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Faltas")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("LancesLivresConvertidos")
                        .HasColumnType("int");

                    b.Property<int>("LancesLivresTentados")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("Rebotes")
                        .HasColumnType("int");

                    b.Property<int>("Roubos")
                        .HasColumnType("int");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.Property<int>("Turnovers")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("TimeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstatisticasPartidas");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Inscricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CampeonatoClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TimeClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("TimeId");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ArbitroClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ArbitroId")
                        .HasColumnType("int");

                    b.Property<Guid>("CampeonatoClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PlacarA")
                        .HasColumnType("int");

                    b.Property<int>("PlacarB")
                        .HasColumnType("int");

                    b.Property<int?>("RodadaDeJogosId")
                        .HasColumnType("int");

                    b.Property<Guid>("TimeAClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeAId")
                        .HasColumnType("int");

                    b.Property<Guid>("TimeBClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeBId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("RodadaDeJogosId");

                    b.HasIndex("TimeAId");

                    b.HasIndex("TimeBId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.PropostaPatrocinio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovada")
                        .HasColumnType("bit");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemPatrocinador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LinkPatrocinador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePatrocinador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatrocinadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorMonetario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("PatrocinadorId");

                    b.ToTable("PropostasPatrocinio");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.RodadaDeJogos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("NomeRodada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RodadasDeJogos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("CapitaoClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapitaoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.HasIndex("CapitaoId")
                        .IsUnique();

                    b.ToTable("Time");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FaixaOrcamentoPatrocinio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("ImagemPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("LinkRedeSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TimeClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.UsuarioCampeonatoFavorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CampeonatoClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioClientAppId", "CampeonatoClientAppId")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "CampeonatoId")
                        .IsUnique();

                    b.ToTable("UsuarioCampeonatoFavoritos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.AvaliacaoArbitro", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Arbitro")
                        .WithMany()
                        .HasForeignKey("ArbitroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.Jogo", "Jogo")
                        .WithMany("AvaliacoesArbitro")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arbitro");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.CampanhaPatrocinio", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Patrocinador")
                        .WithMany()
                        .HasForeignKey("PatrocinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Patrocinador");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Campeonato", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Organizador")
                        .WithMany()
                        .HasForeignKey("OrganizadorId");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Convite", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("IdSolicitanteServidor");

                    b.HasOne("ArenaVirtualAPI.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");

                    b.Navigation("Solicitante");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.EstatisticaPartida", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Jogo", "Jogo")
                        .WithMany("Estatisticas")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Time");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Inscricao", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId");

                    b.HasOne("ArenaVirtualAPI.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId");

                    b.Navigation("Campeonato");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Jogo", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Arbitro")
                        .WithMany()
                        .HasForeignKey("ArbitroId");

                    b.HasOne("ArenaVirtualAPI.Models.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.RodadaDeJogos", "RodadaDeJogos")
                        .WithMany("Jogos")
                        .HasForeignKey("RodadaDeJogosId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArenaVirtualAPI.Models.Time", "TimeA")
                        .WithMany()
                        .HasForeignKey("TimeAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.Time", "TimeB")
                        .WithMany()
                        .HasForeignKey("TimeBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Arbitro");

                    b.Navigation("Campeonato");

                    b.Navigation("RodadaDeJogos");

                    b.Navigation("TimeA");

                    b.Navigation("TimeB");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.PropostaPatrocinio", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Patrocinador")
                        .WithMany()
                        .HasForeignKey("PatrocinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Patrocinador");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Time", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Campeonato", "Campeonato")
                        .WithMany("Times")
                        .HasForeignKey("CampeonatoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArenaVirtualAPI.Models.Usuario", "Capitao")
                        .WithOne("TimeCapitao")
                        .HasForeignKey("ArenaVirtualAPI.Models.Time", "CapitaoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Capitao");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Usuario", b =>
                {
                    b.HasOne("ArenaVirtualAPI.Models.Time", "Time")
                        .WithMany("Membros")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Campeonato", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Jogo", b =>
                {
                    b.Navigation("AvaliacoesArbitro");

                    b.Navigation("Estatisticas");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.RodadaDeJogos", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Time", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ArenaVirtualAPI.Models.Usuario", b =>
                {
                    b.Navigation("TimeCapitao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
